### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by toddwc** [proninyaroslav/blink-comparison#19]
**Question:** Don't recent AI advancements make manual comparisons of tamper labels obsolete? Or am I missing something?   ¯⁠\⁠_⁠(⁠ ͡⁠°⁠ ͜⁠ʖ⁠ ͡⁠°⁠)⁠_⁠/⁠¯  

The Wikipedia article you linked to says astronomers, who invented the technique, haven't used it for decades. But maybe it's still used in other professions.

[**Background:** I clicked on your app in the Google Play Store because I thought it was a way to automatically measure a person's eye blink rate, hopefully by pointing an Android camera at a video screen. 

I recently watched an interview with a convicted serial killer who was blinking just about every second! The criminology professor said (and this is from my failing memory only) that the fast blink rate indicated deception and/or nervousness about being asked for details about one specific crime that involved a child. 

Anyhow, that gave me the idea to see if such an app or Python program existed, as it would be interesting to use it when criminals or others go before TV cameras to profess their innocence. I haven't started looking yet, but the vast majority of my ideas have usually already been executed, so I won't be surprised if I find an open-source project that counts eye-blink rates. :) ]

**Thanks for your time**. ❤️

**Comment by proninyaroslav** [comment]
Maybe it makes sense to improve the app with the help of AI (for example, to help in shooting the most similar photo in terms of distance and angle of view), but the human brain does a good job of comparing with a quick frame change without AI, this was the purpose of the app. In addition, we don't know how perfect the AI will be and whether it will have errors to deceive a person, for example, when comparing tamper-evident seals. And this is quite a critical moment.

**Comment by tlaurion** [comment]
@proninyaroslav as discussed originally, where AI or assistance could be beneficial would be to attempt to trim, or edge discover, borders. Shooting time could still probably be improved instead; the difficulty is holding still while trying to capture against background overlay.

If assistance was there to help match taken picture and make it fit overlay's, I'm not really sure AI would be of really any help here. I think a little bit more assistance, or automatic cropping would be helpful to try to match/resize/reorient taken picture to match overlay.

@toddwc I'm also advocating that blink comparison is a cognitive thing. Literature goes in the same direction. The challenge is more into applying proper seals that cannot be tampered easily with then having an app that does magic.

This is the most thorough article I am aware of https://dys2p.com/en/2021-12-tamper-evident-protection.html

Which links back to the blink comparison app, who finally applied the simple concepts permitting to apply blink comparison cognitive ability in action. Scroll down to see an example. The challenge here, and I repeat, is to reuse similar canva, that is, the same camera angle, distance from object to blink compare more then having AI augment the differences. If you spend more then 3 seconds comparing original seal picture and the actual picture taken, its because you have not found the proper angle to take and retake the same picture twice. Even the lightning conditions don't really matter. Angle and distance matters. Use your fingers to distance yourself at the same distance as a tripod against your tamler seals. Play a bit and you will get it right.

**Comment by tlaurion** [comment]
@proninyaroslav as discussed originally, where AI or assistance could be beneficial would be to attempt to trim, or edge discover, borders. Shooting time could still probably be improved instead; the difficulty is holding still while trying to capture against background overlay.

If assistance was there to help match taken picture and make it fit overlay's, I'm not really sure AI would be of really any help here. I think a little bit more assistance, or automatic cropping would be helpful to try to match/resize/reorient taken picture to match overlay.

@toddwc I'm also advocating that blink comparison is a cognitive thing. Literature goes in the same direction. The challenge is more into applying proper seals that cannot be tampered easily with then having an app that does magic.

This is the most thorough article I am aware of https://dys2p.com/en/2021-12-tamper-evident-protection.html

Which links back to the blink comparison app, who finally applied the simple concepts permitting to apply blink comparison cognitive ability in action. Scroll down to see an example. The challenge here, and I repeat, is to reuse similar canva, that is, the same camera angle, distance from object to blink compare more then having AI augment the differences. If you spend more then 3 seconds comparing original seal picture and the actual picture taken, its because you have not found the proper angle to take and retake the same picture twice. Even the lightning conditions don't really matter. Angle and distance matters. Use your fingers to distance yourself at the same distance as a tripod against your tamler seals. Play a bit and you will get it right.
